In [1]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("anime.csv")
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [4]:
df.shape

(12294, 7)

In [6]:
df.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [8]:
df.describe()

           anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [9]:
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [11]:
df=df.dropna()

In [12]:
df.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
features = df[['genre','rating','members']]
features.head()

                                               genre  rating  members
0               Drama, Romance, School, Supernatural    9.37   200630
1  Action, Adventure, Drama, Fantasy, Magic, Mili...    9.26   793665
2  Action, Comedy, Historical, Parody, Samurai, S...    9.25   114262
3                                   Sci-Fi, Thriller    9.17   673572
4  Action, Comedy, Historical, Parody, Samurai, S...    9.16   151266

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf =TfidfVectorizer (stop_words = 'english')

genre_matrix = tfidf.fit_transform(df['genre'])

In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

numeric_features = scaler.fit_transform(
    df[['rating','members']]
)

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(genre_matrix)

In [19]:
indices = pd.Series(
    df.index,
    index = df['name']
).drop_duplicates()

In [29]:
def recommend_anime(title, top_n=10):

    idx = indices[title]

    sim_scores = list(
        enumerate(cosine_sim[idx])
    )

    sim_scores = sorted(
        sim_scores,
        key=lambda x: x[1],
        reverse=True
    )

    sim_scores = sim_scores[1:top_n+1]

    anime_indices = [i[0] for i in sim_scores]

    return df['name'].iloc[anime_indices]

In [30]:
recommend_anime("Naruto")

615                                    Naruto: Shippuuden
841                                                Naruto
1103    Boruto: Naruto the Movie - Naruto ga Hokage ni...
1343                                          Naruto x UT
1472          Naruto: Shippuuden Movie 4 - The Lost Tower
1573    Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...
2458                 Naruto Shippuuden: Sunny Side Battle
2997    Naruto Soyokazeden Movie: Naruto to Mashin to ...
7628                              Kyutai Panic Adventure!
784            Naruto: Shippuuden Movie 6 - Road to Ninja
Name: name, dtype: object

In [31]:
def recommend_threshold(
    title,
    threshold=0.30
):

    idx = indices[title]

    sim_scores = list(
        enumerate(cosine_sim[idx])
    )

    anime_indices = [
        i[0]
        for i in sim_scores
        if i[1] > threshold
    ]

    return df['name'].iloc[anime_indices]

Performance Analysis:

Strengths:                                                                                                                                             
• Simple and easy to implement.                                                                                                                        
• Fast recommendation generation.                                                                                                                      
• Uses content information effectively.

Limitations:                                                                                                                                           
• Recommendations depend heavily on genre similarity.                                                                                                  
• User preferences are not directly considered.                                                                                                        
• New anime with limited metadata may not receive accurate recommendations.

Conclusion:

A recommendation system was successfully implemented using cosine similarity.

TF-IDF vectorization converted anime genres into numerical representations. Cosine similarity was used to measure similarity between anime titles and generate recommendations.

The system effectively recommends anime with similar content and demonstrates the usefulness of content-based recommendation techniques.

In [ ]:
Interview Questions:

1. Can you explain the difference between user-based and item-based collaborative filtering?


User-Based Collaborative Filtering     
 Finds similar users                                                                                                                      
 Recommends items liked by similar users                                                                                                               
 Computationally expensive                                                                                                                       
 Depends on user behavior                                   


Item-Based Collaborative Filtering 

Finds similar items       
Recommends items similar to those already liked                                                                                                        More scalable                                                                                                                                          Depends on item similarity

2. What is collaborative filtering, and how does it work?

Collaborative Filtering is a recommendation technique that predicts a user's interests based on preferences and behavior of other users.

Working:

Collect user-item interactions.                                                                                                                        
Find similarities among users or items.                                                                                                                
Recommend items based on these similarities.                                                                                                           
Improve recommendations as more data becomes available.